define([], function() {
    return {
        SET_COMPANY: 'SET_COMPANY',
        SET_REDIRECT_TO_CONNECTIONS: 'SET_REDIRECT_TO_CONNECTIONS',
        SET_REDIRECT_TO_OVERVIEW: 'SET_REDIRECT_TO_OVERVIEW',
        SET_SELECT_COMPANY: 'SET_SELECT_COMPANY',
        SET_ACTIVE_FINANCIAL_REPORT: 'SET_ACTIVE_FINANCIAL_REPORT',
        SET_ACTIVE_BUDGET: 'SET_ACTIVE_BUDGET',
        SET_FINANCIAL_REPORT_TAB: 'SET_FINANCIAL_REPORT_TAB',
        SET_BUDGET_TAB: 'SET_BUDGET_TAB',
        SET_INVITATION_COMPANY: 'SET_INVITATION_COMPANY',
        SET_WIDGET_PUBLIC_KEY: 'SET_WIDGET_PUBLIC_KEY'
    };
});
