define([], function() {
   return {
       SET_CASHBOOK_STATE: 'SET_CASHBOOK_STATE',
       SET_BUDGET_STATE: 'SET_BUDGET_STATE',
       SET_AVERAGE_STATE: 'SET_AVERAGE_STATE',
       RESTORE_DASHBOARD_SETTINGS: 'RESTORE_DASHBOARD_SETTINGS',
       SET_FLOATING_AVERAGE: 'SET_FLOATING_AVERAGE_STATE',
       SET_FLOATING_AVERAGE_POINT_SPREAD: 'SET_FLOATING_AVERAGE_POINT_SPREAD',
       SET_PREVIOUS_STATE: 'SET_PREVIOUS_STATE',
       SET_PREVIOUS_TYPE: 'SET_PREVIOUS_TYPE',
       SET_INTERVAL: 'SET_INTERVAL',
       SET_EASYVIEW: 'SET_EASYVIEW',
       SET_KPIS: 'SET_KPIS',
       SET_DASHBOARD_ID: 'SET_DASHBOARD_ID',
       SET_DATE_FROM: 'SET_DATE_FROM',
       SET_DATE_TO: 'SET_DATE_TO',
       SET_PERIODS_DATA: 'SET_PERIODS_DATA'
   };
});