define([], function() {
    return {
        SET_PRESENTATION_EDIT_MODE: 'SET_PRESENTATION_EDIT_MODE',
        SET_PRESENTATION_MODE: 'SET_PRESENTATION_MODE',
        SET_PRESENTATION_ID: 'SET_PRESENTATION_ID',
        SET_PRESENTATION_TOKEN: 'SET_PRESENTATION_TOKEN',
        SET_PRESENTATION_PAGE: 'SET_PRESENTATION_PAGE',
        SET_YEAR_ANNUAL_REPORTS: 'SET_YEAR_ANNUAL_REPORTS',
        SET_SETTINGS_VALUE: 'SET_SETTINGS_VALUE',
        SET_SHOW_PREVIEW: 'SET_SHOW_PREVIEW',
        SET_CLICK_PREVIEW: 'SET_CLICK_PREVIEW',
        SET_OPEN_REPORT: 'SET_OPEN_REPORT',
        SET_REPORT_PRESENTATION: 'SET_REPORT_PRESENTATION',
        SET_FINALIZE_COUNTDOWN: 'SET_FINALIZE_COUNTDOWN',
        SET_TEMPLATES: 'SET_TEMPLATES',
        SET_SAVE_REPORT_PAGE: 'SET_SAVE_REPORT_PAGE'
    };
});
